const Map<String, Map<String, dynamic>> recipes = {
  'Fried Rice': {
    'ingredients': [
      {'ingredient': 'Rice', 'measurement': '2 cups'},
      {'ingredient': 'Mixed vegetables', 'measurement': '1 cup'},
      {'ingredient': 'Eggs', 'measurement': '2'},
      {'ingredient': 'Garlic', 'measurement': '2 cloves'},
      {'ingredient': 'Soy sauce', 'measurement': '2 tablespoons'},
      {'ingredient': 'Oil', 'measurement': '2 tablespoons'},
    ],
    'steps': [
      'Heat oil in a large skillet over medium heat.',
      'Add garlic and sauté until fragrant.',
      'Add mixed vegetables and cook until tender.',
      'Push the vegetables to the side and pour beaten eggs into the skillet.',
      'Scramble the eggs until fully cooked.',
      'Add cooked rice to the skillet and stir to combine.',
      'Pour soy sauce and stir everything together.',
      'Cook for another 2-3 minutes and serve hot.',
    ],
  },
  'Spaghetti Bolognese': {
    'ingredients': [
      {'ingredient': 'Spaghetti', 'measurement': '200g'},
      {'ingredient': 'Ground beef', 'measurement': '500g'},
      {'ingredient': 'Tomato sauce', 'measurement': '2 cups'},
      {'ingredient': 'Onion', 'measurement': '1'},
      {'ingredient': 'Garlic', 'measurement': '2 cloves'},
      {'ingredient': 'Olive oil', 'measurement': '2 tablespoons'},
    ],
    'steps': [
      'Cook spaghetti according to package instructions.',
      'Heat oil in a large skillet over medium heat.',
      'Add chopped onion and garlic, sauté until translucent.',
      'Add ground beef, cook until browned.',
      'Stir in tomato sauce, simmer for 10 minutes.',
      'Serve sauce over spaghetti.',
    ],
  },
  'Pancakes': {
    'ingredients': [
      {'ingredient': 'Flour', 'measurement': '1 cup'},
      {'ingredient': 'Milk', 'measurement': '1 cup'},
      {'ingredient': 'Egg', 'measurement': '1'},
      {'ingredient': 'Baking powder', 'measurement': '1 tablespoon'},
      {'ingredient': 'Salt', 'measurement': '1/2 teaspoon'},
      {'ingredient': 'Butter', 'measurement': '2 tablespoons'},
    ],
    'steps': [
      'In a large bowl, mix flour, baking powder, and salt.',
      'Add milk and egg, whisk until smooth.',
      'Heat a skillet over medium heat, melt butter.',
      'Pour batter into the skillet, cook until bubbles form.',
      'Flip and cook until golden brown.',
      'Serve with syrup.',
    ],
  },
  'Caesar Salad': {
    'ingredients': [
      {'ingredient': 'Romaine lettuce', 'measurement': '1 head'},
      {'ingredient': 'Croutons', 'measurement': '1 cup'},
      {'ingredient': 'Parmesan cheese', 'measurement': '1/2 cup'},
      {'ingredient': 'Caesar dressing', 'measurement': '1/2 cup'},
      {'ingredient': 'Chicken breast', 'measurement': '1'},
      {'ingredient': 'Olive oil', 'measurement': '1 tablespoon'},
    ],
    'steps': [
      'Grill chicken breast until cooked through, slice.',
      'Chop romaine lettuce and place in a large bowl.',
      'Add croutons and Parmesan cheese.',
      'Toss with Caesar dressing.',
      'Top with sliced chicken.',
      'Serve immediately.',
    ],
  },
  'Chili Con Carne': {
    'ingredients': [
      {'ingredient': 'Ground beef', 'measurement': '500g'},
      {'ingredient': 'Kidney beans', 'measurement': '1 can'},
      {'ingredient': 'Tomato sauce', 'measurement': '2 cups'},
      {'ingredient': 'Onion', 'measurement': '1'},
      {'ingredient': 'Garlic', 'measurement': '2 cloves'},
      {'ingredient': 'Chili powder', 'measurement': '2 tablespoons'},
    ],
    'steps': [
      'Heat oil in a large pot over medium heat.',
      'Add chopped onion and garlic, sauté until translucent.',
      'Add ground beef, cook until browned.',
      'Stir in kidney beans, tomato sauce, and chili powder.',
      'Simmer for 20 minutes.',
      'Serve hot.',
    ],
  },
  'Omelette': {
    'ingredients': [
      {'ingredient': 'Eggs', 'measurement': '3'},
      {'ingredient': 'Milk', 'measurement': '1/4 cup'},
      {'ingredient': 'Salt', 'measurement': '1/2 teaspoon'},
      {'ingredient': 'Pepper', 'measurement': '1/4 teaspoon'},
      {'ingredient': 'Cheese', 'measurement': '1/2 cup'},
      {'ingredient': 'Ham', 'measurement': '1/2 cup'},
    ],
    'steps': [
      'Whisk eggs, milk, salt, and pepper in a bowl.',
      'Heat a skillet over medium heat, pour in the egg mixture.',
      'Cook until edges start to set, add cheese and ham.',
      'Fold the omelette in half, cook until cheese melts.',
      'Serve hot.',
    ],
  },
};